apiVersion: v1
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJuZXh1cy1kZXYtZGV2b3BzLm5vbnByb2QudGhlb3Ntby5jb20iOnsidXNlcm5hbWUiOiJkb2NrZXItZGV2LXJ3IiwicGFzc3dvcmQiOiJ6OFh0TTdGSDVrb1QiLCJlbWFpbCI6Im1vLXJlYWR3cml0ZUBNb3RhYmlsaXR5T3BlcmF0aW9ucy5jby51ayIsImF1dGgiOiJaRzlqYTJWeUxXUmxkaTF5ZHpwNk9GaDBUVGRHU0RWcmIxUT0ifX19
kind: Secret
metadata:
  name: nexus-rw