apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- deployment-patch.yaml
namePrefix: product-
commonLabels:
  service: product

configMapGenerator:
- files:
  - application.properties
  name: product-config

images:
- name: image
  newName: quay.io/justindav1s/product
  newTag: ae71991

replicas:
- name: product-deployment
  count: 1    

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: product-deployment
  path: deployment-json-patches.yaml
- target:
    group: route.openshift.io
    version: v1
    kind: Route
    name: product-route
  path: route-json-patches.yaml
- target:
    group:
    version: v1
    kind: Service
    name: product-service
  path: service-json-patches.yaml  
