---
kind: Template
apiVersion: v1
metadata:
  labels:
    app: mongodb
  name: mongodb
  annotations:
    openshift.io/display-name: Deploy Mongodb
    description: Deploy Mongodb
    tags: mongodb
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    labels:
      name: mongodb
      app: mongodb
    name: mongodb-internal
  spec:
    ports:
    - name: 27017-tcp
      port: 27017
    clusterIP: None
    selector:
      name: "mongodb"

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      name: mongodb
      app: mongodb
    name: mongodb
  spec:
    ports:
    - name: 27017-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: mongodb

- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    labels:
      app: mongodb
    name: mongodb
  spec:
    replicas: ${REPLICAS}
    serviceName: mongodb-internal
    selector:
      matchLabels:
        name: mongodb
    template:
      metadata:
        labels:
          name: mongodb
      spec:
        serviceAccount: default
        serviceAccountName: default
        containers:
        - image: registry.access.redhat.com/rhscl/mongodb-32-rhel7
          ports:
          - containerPort: 27017
            name: mongodb
          volumeMounts:
          - name: mongo
            mountPath: /var/lib/mongodb/data
          name: mongodb
          args: ["run-mongod-replication" ]
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          readinessProbe:
            exec:
              command:
              - stat
              - /tmp/initialized
          env:
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mongodb
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mongodb
          - name: MONGODB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-admin-password
                name: mongodb
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: mongodb
          - name: MONGODB_REPLICA_NAME
            value: ${MONGODB_REPLICA_NAME}
          - name: MONGODB_KEYFILE_VALUE
            value: ${MONGODB_KEYFILE_VALUE}
          - name: MONGODB_SERVICE_NAME
            value: "mongodb-internal"
    volumeClaimTemplates:
    - metadata:
        name: mongo
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: ${VOLUME_CAPACITY}

- apiVersion: v1
  kind: Secret
  stringData:
    database-admin-password: ${MONGODB_ADMIN_PASSWORD}
    database-name: ${MONGODB_DATABASE}
    database-password: ${MONGODB_PASSWORD}
    database-user: ${MONGODB_USER}
  metadata:
    labels:
      app: mongodb
    name: mongodb
  type: Opaque

parameters:
- description: the number of mongodbs required in the statefulset.
  name: REPLICAS
  required: true
  value: "1"
- name: VOLUME_CAPACITY
  displayName: "Volume Capacity"
  description: "Volume space available for data, e.g. 512Mi, 2Gi."
  value: "1Gi"
  required: true
- name: MEMORY_LIMIT
  displayName: "Memory Limit"
  description: "Maximum amount of memory the container can use."
  value: "512Mi"
- name: MONGODB_USER
  displayName: "MongoDB Connection Username"
  description: "Username for MongoDB user that will be used for accessing the database."
  generate: expression
  from: "[a-zA-Z0-9]{3}"
  required: true
- name: MONGODB_PASSWORD
  displayName: "MongoDB Connection Password"
  description: "Password for the MongoDB connection user."
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true
- name: MONGODB_DATABASE
  displayName: "MongoDB Database Name"
  description: "Name of the MongoDB database accessed."
  value: sampledb
  required: true
- name: MONGODB_ADMIN_PASSWORD
  displayName: "MongoDB Admin Password"
  description: "Password for the database admin user."
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true
- name: MONGODB_REPLICA_NAME
  displayName: "Replica Set Name"
  description: "The name of the replica set."
  value: rs0
  required: true
- name: MONGODB_KEYFILE_VALUE
  displayName: "Keyfile Content"
  description: "The value of the MongoDB keyfile (https://docs.mongodb.com/manual/core/security-internal-authentication/#internal-auth-keyfile)."
  generate: expression
  from: "[a-zA-Z0-9]{255}"
  required: true