apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: websso-dev-dc
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: websso
    name: websso
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: websso
      deploymentconfig: web
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: websso
          deploymentconfig: web
      spec:
        containers:
        - name: websso
          image: " "
          imagePullPolicy: Always
          env:
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: websso
    name: websso
  spec:
    ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
    selector:
      app: websso
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: websso
    name: websso
  spec:
    port:
      targetPort: http
    to:
      kind: Service
      name: websso
      weight: 100
    wildcardPolicy: None