spring:
  application:
    name: api-gateway.build.test

server:
  port: 8081

basket:
  host: basket-amazin-dev.apps.ocp.datr.eu

inventory:
  host: inventory-amazin-dev.apps.ocp.datr.eu

user:
  host: user-amazin-dev.apps.ocp.datr.eu

opentracing:
  jaeger:
    enable-b3-propagation: true
    opentracing.jaeger.expand-exception-logs: true
    http-sender:
      url: http://jaeger-collector.istio-system.svc:14268/api/traces

keycloak:
  enabled: true
  auth-server-url: http://127.0.0.1:8080/auth
  resource: webapp
  realm: amazin
  credentials.secret: cc48f8ad-80d3-4019-8d36-7dfb6f5c86e7
  use-resource-role-mappings: true
  principal-attribute: preferred_username
  securityConstraints[0]:
    authRoles[0]: product
  securityCollections[0]:
    name: products
    patterns[0]: /api
