server:
  port: 8081

basket:
  host: basket-amazin-dev.apps.ocp.datr.eu

inventory:
  host: inventory-amazin-dev.apps.ocp.datr.eu

user:
  host: user-amazin-dev.apps.ocp.datr.eu

logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  application:
    name: api-gateway-test
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/auth/realms/amazin