kind: Template
apiVersion: v1
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_LABEL}
      name: ${RESOURCE_NAME}
    stringData:
        enterprise-jdbcurl: ${ENTERPRISE_JDBC_URL}
        enterprise-user: ${ENTERPRISE_USER}
        enterprise-password: ${ENTERPRISE_PASSWORD}
        eventdb-jdbc-url: ${EVENTDB_JDBC_URL}
        eventdb-user: ${EVENTDB_JPA_USER}
        eventdb-password: ${EVENTDB_JPA_PASSWORD}
        aws-sqs-queue-name: ${AWS_SQS_QUEUE_NAME}
        aws-sqs-access-key: ${AWS_SQS_ACCESS_KEY}
        aws-sqs-secret-key: ${AWS_SQS_SECRET_KEY}
        aws-sqs-region: ${AWS_SQS_REGION}
parameters:
  - name: RESOURCE_NAME
    displayName: Resource Name
    description: The name of the service resource that also matches POD app label.
    required: true
  - name: APP_LABEL
    displayName: Application Label
    description: Name of the application label that should be used in all resources.
    required: true
  - name: ENTERPRISE_JDBC_URL
    displayName: Enterprise JDBC URL
    description: The database JDBC URL connection string.
    required: true
  - name: ENTERPRISE_USER
    displayName: Enterprise User
    description: The name of the Enterprise user.
    required: true
  - name: ENTERPRISE_PASSWORD
    displayName: Enterprise Password
    description: The name of the Enterprise user password.
    required: true
  - name: EVENTDB_JDBC_URL
    displayName: Event DB JDBC URL
    description: The database JDBC URL connection string.
    required: true
  - name: EVENTDB_JPA_USER
    displayName: Event DB User
    description: The name of the Event DB  user.
    required: true
  - name: EVENTDB_JPA_PASSWORD
    displayName: Event DB Password
    description: The name of the Event DB user password.
    required: true
  - name: AWS_SQS_QUEUE_NAME
    displayName: AWS SQS queue name
    description: The name of the ASW SQS queue to receive message from.
    required: true
  - name: AWS_SQS_ACCESS_KEY
    displayName: AWS SQS access key
    description: The AWS SQS access key.
    required: true
  - name: AWS_SQS_SECRET_KEY
    displayName: AWS SQS secret key
    description: The AWS SQS secret key.
    required: true
  - name: AWS_SQS_REGION
    displayName: AWS SQS Region
    description: The AWS SQS Region.
    required: true
