apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resource-quota.yaml
- limit-range.yaml
- jenkins-edit-rb.yaml

commonAnnotations:
  author: Justin Davis

secretGenerator:
- name: crc-nexus-dockercfg
  files:
  - .dockerconfigjson=secrets/crc-dockerconfig.json
  type: "kubernetes.io/dockerconfigjson"
- name: rhpds-nexus-dockercfg
  files:
  - .dockerconfigjson=secrets/rhpds-dockerconfig.json
  type: "kubernetes.io/dockerconfigjson" 
- name: datreu-nexus-dockercfg
  files:
  - .dockerconfigjson=secrets/datreu-dockerconfig.json
  type: "kubernetes.io/dockerconfigjson"
- name: selfsigned-certs
  files:
  - secrets/tls.crt
  - secrets/tls.key
  type: "kubernetes.io/tls"    
