apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}
objects:

- apiVersion: v1
  kind: Pod
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    containers:
      - args:
          - '--dockerfile=/tmp/app/Dockerfile'
          - '--context=dir://tmp/app'
          - '--destination=docker-registry.default.svc.cluster.local:5000/kaniko-test/example'
          - '--skip-tls-verify'
        image: 'gcr.io/kaniko-project/executor:latest'
        name: kaniko
        volumeMounts:
          - mountPath: /tmp/app
            name: app-volume
          - mountPath: /kaniko/.docker
            name: docker-config-volume
          - mountPath: /root/.docker
            name: docker-config-volume
    restartPolicy: Never
    serviceAccount: builder
    serviceAccountName: builder
    volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: app-volume-claim
      - name: docker-config-volume
        persistentVolumeClaim:
          claimName: docker-config-volume-claim

parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: kaniko