
package com.employee.service.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-01-29T16:13:59.109-05:00
 * Generated source version: 3.4.2
 */

@WebFault(name = "createEmployeeFault", targetNamespace = "http://service.employee.com/types/v1")
public class CreateEmployeeFault extends Exception {

    private com.employee.service.types.v1.CreateEmployeeFault faultInfo;

    public CreateEmployeeFault() {
        super();
    }

    public CreateEmployeeFault(String message) {
        super(message);
    }

    public CreateEmployeeFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CreateEmployeeFault(String message, com.employee.service.types.v1.CreateEmployeeFault createEmployeeFault) {
        super(message);
        this.faultInfo = createEmployeeFault;
    }

    public CreateEmployeeFault(String message, com.employee.service.types.v1.CreateEmployeeFault createEmployeeFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = createEmployeeFault;
    }

    public com.employee.service.types.v1.CreateEmployeeFault getFaultInfo() {
        return this.faultInfo;
    }
}
