kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "product.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ include "product.fullname" . }}
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None