kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment
spec:
  template:
    spec:
      serviceAccountName: user-sa
      containers:
        - name: container
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prd
          volumeMounts:
            - mountPath: /config
              name: user-config-vol      
      volumes:
      - configMap:
          defaultMode: 420
          name: user-config
        name: user-config-vol                                     