apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
patchesStrategicMerge:
- deployment-patch.yaml
namePrefix: user-
commonLabels:
  service: user

images:
- name: image
  newName: nexus3-docker-cicd.apps.ocp4.datr.eu/repository/docker/amazin-dev/user
  newTag: latest

replicas:
- name: user-deployment
  count: 1

configMapGenerator:
- files:
  - config.properties
  name: user-config

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: user-deployment
  path: deployment-json-patches.yaml
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: user-ingress
  path: ingress-json-patches.yaml
- target:
    group:
    version: v1
    kind: Service
    name: user-service
  path: service-json-patches.yaml     