kind: ConfigMap
apiVersion: v1
metadata:
  name: serviceb-config
  namespace: amazin-serverless
data:
  application.properties: |
    config.test.data.2=This is Config Data 2
---
apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: serviceb-native
  namespace: amazin-serverless
  labels:
    serving.knative.dev/visibility: cluster-local  
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: 'quay.io/justindav1s/serviceb-native:463849d'       
    spec:
      containerConcurrency: 1
      containers:
        - env:
            - name: TARGET
              value: Knative
          image: 'quay.io/justindav1s/serviceb-native:463849d'
          name: user-container
          resources: {}
          volumeMounts:
            - name: config-vol
              mountPath: /work/config
      timeoutSeconds: 300
      volumes:
        - name: config-vol
          configMap:
            name: serviceb-config
            defaultMode: 420
  traffic:
    - latestRevision: true
      percent: 100