spring:
  application:
    name: api-gateway.build.test

server:
  port: 8080

basket:
  host: basket.amazin-dev.svc:8080

inventory:
  host: inventory.amazin-dev.svc:8080

user:
  host: user.amazin-dev.svc:8080

opentracing:
  jaeger:
    enable-b3-propagation: true
    opentracing.jaeger.expand-exception-logs: true
    http-sender:
      url: http://jaeger-collector.istio-system.svc:14268/api/traces

