apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: amazin-dev-quay-secret
    data:
      .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LWVudGVycHJpc2UtcXVheS1lbnRlcnByaXNlLmFwcHMub2NwLmRhdHIuZXUiOiB7CiAgICAgICJhdXRoIjogIllXMWhlbWx1TFdSbGRpdHFaVzVyYVc1ek9qSlhNelZUV0ZWUk1EVk1NRVpUVTB4WFdVWlFVMDFYV2tvNU9WaFJTVFk1UkRkTVNrbFdRa2d6TVVGYVVsWkpXbEZLV1ZjNU9EUTNNakJaTkVaSFIwOD0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
    type: kubernetes.io/dockerconfigjson

  - apiVersion: v1
    kind: Secret
    metadata:
      name: quay-dev-quay-secret
    data:
      .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LWVudGVycHJpc2UtcXVheS1lbnRlcnByaXNlLmFwcHMub2NwLmRhdHIuZXUiOiB7CiAgICAgICJhdXRoIjogImNYVmhlUzFrWlhZcmFtVnVhMmx1Y3pvNU9VWldTRmROT1VKQlZFWllSamszUnpOSlZWQXpXa0pNVTB0QlN6aFBWalJhVERVeldqSk9PRlE1UVRsWVNFNDVWekpaUXpGQlQwb3hNakpLVWtVMyIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
    type: kubernetes.io/dockerconfigjson

  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}-sa

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APPLICATION_NAME}
      annotations:
        openshift.io/display-name: ${APPLICATION_NAME}
    spec:
      dockerImageRepository: quay-enterprise-quay-enterprise.apps.ocp.datr.eu/${PROJECT}/${APPLICATION_NAME}

  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      output:
        pushSecret:
          name: quay-dev-quay-secret
        to:
          kind: DockerImage
          name: quay-enterprise-quay-enterprise.apps.ocp.datr.eu/${PROJECT}/${APPLICATION_NAME}:${BUILD_TAG}
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        binary: {}
        type: Binary
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: ${BASE_IMAGE}
            namespace: ${BASE_IMAGE_NAMESPACE}
        type: Source

  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      replicas: 1
      selector:
        app: ${APPLICATION_NAME}
        deploymentconfig: ${APPLICATION_NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
          labels:
            app: ${APPLICATION_NAME}
            deploymentconfig: ${APPLICATION_NAME}
        spec:
          serviceAccountName: ${APPLICATION_NAME}-sa
          containers:
            - env:
                - name: SPRING_PROFILES_ACTIVE
                  value: dev
              image: ' '
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              name: ${APPLICATION_NAME}
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /config
                  name: ${APPLICATION_NAME}-config-vol
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - configMap:
                defaultMode: 420
                name: ${APPLICATION_NAME}-config
              name: ${APPLICATION_NAME}-config-vol

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${APPLICATION_NAME}
        weight: 100
      wildcardPolicy: None

  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: ${APPLICATION_NAME}
        deploymentconfig: ${APPLICATION_NAME}
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
      
parameters:
  - description: The name for the application.
    name: APPLICATION_NAME
    required: true
    value: basket
  - description: The name for the application.
    name: PROJECT
    required: true
    value: inventory
  - description: The name for the application.
    name: BUILD_TAG
    required: true
    value: build_tag_default
  - description: Base Docker image namespace.
    name: BASE_IMAGE_NAMESPACE
    required: true
    value: "openshift"
  - description: Base Docker image.
    name: BASE_IMAGE
    required: true
    value: "java:8"