kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: argocd-project2-admins
users:
  - justin
  - project2
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: argocd-project2-ro
users:
  - project2-ro