apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project2-app
spec:
  destination:
    namespace: project2-dev
    server: 'https://kubernetes.default.svc'
  project: argocd-project2
  source:
    path: cicd_tools/argocd/rbac-test/project2-app
    repoURL: 'git@github.com:justindav1s/microservices-on-openshift.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    