apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project1-app
spec:
  destination:
    namespace: project1-dev
    server: 'https://kubernetes.default.svc'
  project: argocd-project1
  source:
    path: cicd_tools/argocd/rbac-test/project1-app
    repoURL: 'git@github.com:justindav1s/microservices-on-openshift.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    