apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml

secretGenerator:
- name: nexus-dockercfg
  files:
  - .dockerconfigjson=secrets/nexus-dockerconfig.json
  type: "kubernetes.io/dockerconfigjson"