<?xml version='1.1' encoding='UTF-8'?>
<hudson>
  <disabledAdministrativeMonitors>
    <string>OldData</string>
    <string>jenkins.diagnostics.RootUrlNotSetMonitor</string>
    <string>jenkins.security.csrf.CSRFAdministrativeMonitor</string>
    <string>jenkins.security.s2m.MasterKillSwitchWarning</string>
  </disabledAdministrativeMonitors>
  <version>2.121.3</version>
  <installStateName>RESTART</installStateName>
  <numExecutors>5</numExecutors>
  <mode>NORMAL</mode>
  <useSecurity>true</useSecurity>
  <authorizationStrategy class="hudson.security.GlobalMatrixAuthorizationStrategy">
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Create:admin</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Create:justin-admin-edit-view</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Delete:admin</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Delete:justin-admin-edit-view</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains:admin</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains:justin-admin-edit-view</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Update:admin</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Update:justin-admin-edit-view</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.View:admin</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.View:justin-admin-edit-view</permission>
    <permission>hudson.model.Computer.Build:admin</permission>
    <permission>hudson.model.Computer.Configure:admin</permission>
    <permission>hudson.model.Computer.Configure:justin-admin-edit-view</permission>
    <permission>hudson.model.Computer.Connect:admin</permission>
    <permission>hudson.model.Computer.Create:admin</permission>
    <permission>hudson.model.Computer.Delete:admin</permission>
    <permission>hudson.model.Computer.Delete:justin-admin-edit-view</permission>
    <permission>hudson.model.Computer.Disconnect:admin</permission>
    <permission>hudson.model.Hudson.Administer:admin</permission>
    <permission>hudson.model.Hudson.Administer:justin-admin-edit-view</permission>
    <permission>hudson.model.Hudson.Read:admin</permission>
    <permission>hudson.model.Hudson.Read:justin-admin-edit-view</permission>
    <permission>hudson.model.Item.Build:admin</permission>
    <permission>hudson.model.Item.Build:justin-admin-edit-view</permission>
    <permission>hudson.model.Item.Cancel:admin</permission>
    <permission>hudson.model.Item.Cancel:justin-admin-edit-view</permission>
    <permission>hudson.model.Item.Configure:admin</permission>
    <permission>hudson.model.Item.Configure:justin-admin-edit-view</permission>
    <permission>hudson.model.Item.Create:admin</permission>
    <permission>hudson.model.Item.Create:justin-admin-edit-view</permission>
    <permission>hudson.model.Item.Delete:admin</permission>
    <permission>hudson.model.Item.Delete:justin-admin-edit-view</permission>
    <permission>hudson.model.Item.Discover:admin</permission>
    <permission>hudson.model.Item.Discover:justin-admin-edit-view</permission>
    <permission>hudson.model.Item.Move:admin</permission>
    <permission>hudson.model.Item.Read:admin</permission>
    <permission>hudson.model.Item.Read:justin-admin-edit-view</permission>
    <permission>hudson.model.Item.Workspace:admin</permission>
    <permission>hudson.model.Item.Workspace:justin-admin-edit-view</permission>
    <permission>hudson.model.Run.Delete:admin</permission>
    <permission>hudson.model.Run.Delete:justin-admin-edit-view</permission>
    <permission>hudson.model.Run.Replay:admin</permission>
    <permission>hudson.model.Run.Update:admin</permission>
    <permission>hudson.model.Run.Update:justin-admin-edit-view</permission>
    <permission>hudson.model.View.Configure:admin</permission>
    <permission>hudson.model.View.Configure:justin-admin-edit-view</permission>
    <permission>hudson.model.View.Create:admin</permission>
    <permission>hudson.model.View.Create:justin-admin-edit-view</permission>
    <permission>hudson.model.View.Delete:admin</permission>
    <permission>hudson.model.View.Delete:justin-admin-edit-view</permission>
    <permission>hudson.model.View.Read:admin</permission>
    <permission>hudson.scm.SCM.Tag:admin</permission>
    <permission>hudson.scm.SCM.Tag:justin-admin-edit-view</permission>
    <permission>org.jenkins.plugins.lockableresources.LockableResourcesManager.Reserve:admin</permission>
    <permission>org.jenkins.plugins.lockableresources.LockableResourcesManager.Unlock:admin</permission>
  </authorizationStrategy>
  <!--<securityRealm class="org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm" plugin="openshift-login@1.0.11"/>-->
  <disableRememberMe>false</disableRememberMe>
  <projectNamingStrategy class="jenkins.model.ProjectNamingStrategy$DefaultProjectNamingStrategy"/>
  <workspaceDir>${ITEM_ROOTDIR}/workspace</workspaceDir>
  <buildsDir>${ITEM_ROOTDIR}/builds</buildsDir>
  <markupFormatter class="hudson.markup.EscapedMarkupFormatter"/>
  <jdks/>
  <viewsTabBar class="hudson.views.DefaultViewsTabBar"/>
  <myViewsTabBar class="hudson.views.DefaultMyViewsTabBar"/>
  <clouds>
    <org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud plugin="kubernetes@1.13.7">
      <name>openshift</name>
      <templates>
        <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
          <inheritFrom></inheritFrom>
          <name>maven</name>
          <privileged>false</privileged>
          <capOnlyOnAlivePods>false</capOnlyOnAlivePods>
          <alwaysPullImage>false</alwaysPullImage>
          <instanceCap>2147483647</instanceCap>
          <slaveConnectTimeout>0</slaveConnectTimeout>
          <idleMinutes>0</idleMinutes>
          <activeDeadlineSeconds>0</activeDeadlineSeconds>
          <label>maven</label>
          <serviceAccount>jenkins</serviceAccount>
          <nodeSelector></nodeSelector>
          <customWorkspaceVolumeEnabled>false</customWorkspaceVolumeEnabled>
          <volumes/>
          <containers>
            <org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
              <name>jnlp</name>
              <image>registry.redhat.io/openshift3/jenkins-agent-maven-35-rhel7:v3.11</image>
              <privileged>false</privileged>
              <alwaysPullImage>true</alwaysPullImage>
              <workingDir>/tmp</workingDir>
              <command></command>
              <args>${computer.jnlpmac} ${computer.name}</args>
              <ttyEnabled>false</ttyEnabled>
              <resourceRequestCpu></resourceRequestCpu>
              <resourceRequestMemory></resourceRequestMemory>
              <resourceLimitCpu></resourceLimitCpu>
              <resourceLimitMemory></resourceLimitMemory>
              <envVars/>
            </org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
          </containers>
          <envVars/>
          <annotations/>
          <imagePullSecrets/>
          <nodeProperties/>
          <podRetention class="org.csanchez.jenkins.plugins.kubernetes.pod.retention.Default"/>
        </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
        <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
          <inheritFrom></inheritFrom>
          <name>nodejs</name>
          <privileged>false</privileged>
          <capOnlyOnAlivePods>false</capOnlyOnAlivePods>
          <alwaysPullImage>false</alwaysPullImage>
          <instanceCap>2147483647</instanceCap>
          <slaveConnectTimeout>0</slaveConnectTimeout>
          <idleMinutes>0</idleMinutes>
          <activeDeadlineSeconds>0</activeDeadlineSeconds>
          <label>nodejs</label>
          <serviceAccount>jenkins</serviceAccount>
          <nodeSelector></nodeSelector>
          <customWorkspaceVolumeEnabled>false</customWorkspaceVolumeEnabled>
          <volumes/>
          <containers>
            <org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
              <name>jnlp</name>
              <image>registry.redhat.io/openshift3/jenkins-agent-nodejs-8-rhel7:v3.11</image>
              <privileged>false</privileged>
              <alwaysPullImage>true</alwaysPullImage>
              <workingDir>/tmp</workingDir>
              <command></command>
              <args>${computer.jnlpmac} ${computer.name}</args>
              <ttyEnabled>false</ttyEnabled>
              <resourceRequestCpu></resourceRequestCpu>
              <resourceRequestMemory></resourceRequestMemory>
              <resourceLimitCpu></resourceLimitCpu>
              <resourceLimitMemory></resourceLimitMemory>
              <envVars/>
            </org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
          </containers>
          <envVars/>
          <annotations/>
          <imagePullSecrets/>
          <nodeProperties/>
          <podRetention class="org.csanchez.jenkins.plugins.kubernetes.pod.retention.Default"/>
        </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
      </templates>
      <serverUrl>https://172.30.0.1:443</serverUrl>
      <serverCertificate>-----BEGIN CERTIFICATE-----
MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE1NDQwMjYyNjYwHhcNMTgxMjA1MTYxMTA1WhcNMjMxMjA0
MTYxMTA2WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1NDQwMjYyNjYw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCkmaIRnCBpwozqSKrUkpjC
OhtN9L30PzeTUH+37VMt5B0DxHRrza4CKoZPXe68Ws/Eh5/4g+xvsqT0cpqxYGTm
Bqmmh3XFSgEHhxhdANhqiz3/BeLko9e5wVToIWMrGkPKN1/0bcOIrALzTD8yYtV9
WTsQReAHC2b7BHUn0dGCBuJA24Iqdv8GE3Y1DaYFe9pcnbiaLgf9OKVnQEcWSfl9
njgdeHcqBv1OLKT4W2HocFhOzQnzSHFQxuOcT8CuXmsBKiAvZ8CYx0SDh3YsC1RQ
QbMu0Lv+E/PF3HUFk6FNyIDSoOEzaatNLeFHmuRQ/TzgU/MkX/cXZgfN0gYNvu/Z
AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
SIb3DQEBCwUAA4IBAQAVm1Kc93eiKo+y39yLpeFTo5LFjjG62chvfZh5gpMr7HqY
2S6mYz84wWHi2aOIak/9tG3yEw3QAHoox2P/zafgy81j5cX3DKSSQpzDNfCPyj9z
8nOkcaMsCbbSlFjEEWoLJIpXsYKg4eoekY/2IO3eOTVDuIMnUs6IwMLgyPMDyeKB
FmXl4f8BgyXrm9c6XAPZx8sKFHsQYtuQLESr0PPJ2qDKUjTQLy8sY1VgsnZlfOZB
yT4pGyjcE6f/YCDexhinttfXj3jytkfcz1jVj7iMhG51Xe+otagk3LAZSNxxfT61
7Esgots8Co8oJxDGd+fXe9G0s1ZEVEaa/dudMP/t
-----END CERTIFICATE-----</serverCertificate>
      <skipTlsVerify>false</skipTlsVerify>
      <addMasterProxyEnvVars>true</addMasterProxyEnvVars>
      <capOnlyOnAlivePods>false</capOnlyOnAlivePods>
      <namespace>${OPENSHIFT_BUILD_NAMESPACE}</namespace>
      <jenkinsUrl>http://jenkins.${OPENSHIFT_BUILD_NAMESPACE}.svc:80</jenkinsUrl>
      <jenkinsTunnel>jenkins-jnlp.${OPENSHIFT_BUILD_NAMESPACE}.svc:50000</jenkinsTunnel>
      <credentialsId>1a12dfa4-7fc5-47a7-aa17-cc56572a41c7</credentialsId>
      <containerCap>100</containerCap>
      <retentionTimeout>5</retentionTimeout>
      <connectTimeout>0</connectTimeout>
      <readTimeout>0</readTimeout>
      <usageRestricted>false</usageRestricted>
      <maxRequestsPerHost>32</maxRequestsPerHost>
      <podRetention class="org.csanchez.jenkins.plugins.kubernetes.pod.retention.Never"/>
    </org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud>
  </clouds>
  <quietPeriod>1</quietPeriod>
  <scmCheckoutRetryCount>0</scmCheckoutRetryCount>
  <views>
    <hudson.model.AllView>
      <owner class="hudson" reference="../../.."/>
      <name>all</name>
      <filterExecutors>false</filterExecutors>
      <filterQueue>false</filterQueue>
      <properties/>
    </hudson.model.AllView>
  </views>
  <primaryView>all</primaryView>
  <slaveAgentPort>50000</slaveAgentPort>
  <disabledAgentProtocols>
    <string>JNLP-connect</string>
    <string>JNLP2-connect</string>
  </disabledAgentProtocols>
  <label>master</label>
  <crumbIssuer class="hudson.security.csrf.DefaultCrumbIssuer">
    <excludeClientIPFromCrumb>true</excludeClientIPFromCrumb>
  </crumbIssuer>
  <nodeProperties/>
  <globalNodeProperties/>
  <noUsageStatistics>true</noUsageStatistics>
</hudson>