camel:
  springboot:
    name: @project.name@
    main-run-controller: true

sftp:
  host: ocp.datr.eu
  port: 22
  username: justin
  passphrase: ""
  path: "/tmp"
  keyfile: /deployments/keys/private_key.pem