kind: Template
apiVersion: v1
metadata:
  labels:
    app: ${APPLICATION_NAME}
  annotations:
    description: The SonarQube OpenShift template
    tags: instant-app, ${APPLICATION_NAME}
  name: sonarqube-persistent-template
message: "Login to SonarQube with the default admin basket: admin/admin"
objects:


- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-docker-build"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    triggers: []
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: ${DOCKERFILE_PATH}
    strategy:
      dockerStrategy:
        dockerfilePath: ${DOCKERFILE_NAME}
        env:
          - name: "SONARQUBE_VERSION"
            value: "${SONARQUBE_VERSION}"
          - name: "DOCKERFILE_PATH"
            value: "${DOCKERFILE_PATH}"
    output:
      to:    
        kind: "DockerImage"
        name: "${REG_HOST}/justindav1s/${APPLICATION_NAME}:${SONARQUBE_VERSION}"
      pushSecret:
        name: reg-dockercfg      
    resources: {}
    postCommit: {}
    
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
          tuned.openshift.io/elasticsearch: ""
      spec:
        serviceAccountName: ${APPLICATION_NAME}
        containers:
        - env:
          - name: SONARQUBE_JDBC_PASSWORD
            value: ${SONARQUBE_JDBC_PASSWORD}
          - name: SONARQUBE_JDBC_URL
            value: ${SONARQUBE_JDBC_URL}
          - name: SONARQUBE_JDBC_USERNAME
            value: ${SONARQUBE_JDBC_USERNAME}
          image: ' '
          imagePullPolicy: IfNotPresent
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 9000
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            httpGet:
              port: 9000
              path: /
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            httpGet:
              port: 9000
              path: /
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/sonarqube/data
            name: ${APPLICATION_NAME}-data
          - mountPath: /opt/sonarqube/extensions
            name: ${APPLICATION_NAME}-extensions
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${APPLICATION_NAME}-data
          persistentVolumeClaim:
            claimName: ${APPLICATION_NAME}-data
        - name: ${APPLICATION_NAME}-extensions
          persistentVolumeClaim:
            claimName: ${APPLICATION_NAME}-extensions
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:${SONARQUBE_VERSION}
      type: ImageChange

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: ${APPLICATION_NAME}-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${SONAR_VOLUME_CAPACITY}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: ${APPLICATION_NAME}-extensions
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${SONAR_VOLUME_CAPACITY}

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name":"postgresl","namespace":"","kind":"Service"}]'
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    ports:
    - name: ${APPLICATION_NAME}
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for SonarQube's http service.
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: sonarqube
- description: Git source URI for application
  name: SOURCE_REPOSITORY_URL
  value: ""
  required: true
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: "master"
  required: false
- name: DOCKERFILE_PATH
  displayName: Dockerfile path
  description: Path within Git Repo wehere Dockerfile can be found.
  value: ""
  required: false
- name: DOCKERFILE_NAME
  displayName: Dockerfile name
  description: Name of Dockerfile.
  value: "Dockerfile"
  required: true
- displayName: SonarQube version
  value: "7.9"
  name: SONARQUBE_VERSION
  required: true
- description: Username for SonarQube Server PostgreSQL backend
  displayName: SonarQube's PostgreSQL Username
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: SONARQUBE_JDBC_USERNAME
  required: true
- description: Password for SonarQube Server PostgreSQL backend
  displayName: SonarQube's PostgreSQL Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: SONARQUBE_JDBC_PASSWORD
  required: true
- description: URL for SonarQube Server PostgreSQL backend
  displayName: SonarQube's PostgreSQL URL
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name:  SONARQUBE_JDBC_URL
  value: "jdbc:postgresql://postgres-cicd/cicd"
- description: Volume space available for SonarQube
  displayName: SonarQube Volume Capacity
  name: SONAR_VOLUME_CAPACITY
  required: true
  value: 2Gi
- description: Registry host used to store image
  displayName: Registry host
  name: REG_HOST
  required: true