apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
patchesStrategicMerge:
- deployment-patch.yaml
namePrefix: api-gateway-
commonLabels:
  service: api-gateway

configMapGenerator:
- files:
  - config.properties
  name: api-gateway-config

replicas:
- name: api-gateway-deployment
  count: 1
  
images:
- name: image
  newName: nexus3-docker-cicd.apps.ocp4.datr.eu/repository/docker/amazin-dev/api-gateway
  newTag: latest    

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: api-gateway-deployment
  path: deployment-json-patches.yaml
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: api-gateway-ingress
  path: ingress-json-patches.yaml  
- target:
    group:
    version: v1
    kind: Service
    name: api-gateway-service
  path: service-json-patches.yaml    