apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- namespace.yaml
- ../base
- serviceaccounts.yaml
- nexus.yaml
- postgres.yaml
- sonarqube.yaml
namespace: cicd

patchesStrategicMerge:
- dockercfg-sonarqube-patch.yaml  
