---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: java-build
spec:
  serviceAccount: default
  inputs:
    resources:
      - name: checkout
        resourceSpec:
          type: git
          params:
            - name: revision
              value: master
            - name: url
              value: https://github.com/justindav1s/microservices-on-openshift.git
  taskSpec:
    inputs:
      resources:
        - name: checkout
          type: git
    steps:
      - name: check-dir
        image: docker-registry.default.svc:5000/tekton-test2/java-builder
        workingDir: '/workspace/checkout/src/inventory'
        command: ["/bin/bash"]
        args: ["-c", "ls -ltr"]
      - name: mvn-package
        image: docker-registry.default.svc:5000/tekton-test2/java-builder
        workingDir: '/workspace/checkout/src/inventory'
        command: ["/bin/bash"]
        args: ["-c", "mvn -B -U -q -s ../settings.xml -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -DskipTests package "]
      - name: mvn-test
        image: docker-registry.default.svc:5000/tekton-test2/java-builder
        workingDir: '/workspace/checkout/src/inventory'
        command: ["/bin/bash"]
        args: ["-c", "mvn -B -U -q -s ../settings.xml -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dspring.profiles.active=dev test "]
      - name: mvn-deploy
        image: docker-registry.default.svc:5000/tekton-test2/java-builder
        workingDir: '/workspace/checkout/src/inventory'
        command: ["/bin/bash"]
        args: ["-c", "mvn -B -U -q -s ../settings.xml -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -DskipTests deploy"]
