apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: web-prod-dc
objects:

#don't want istio injection for web gui, this is simply an nginx that provides an angular app to the browser
#annotation sidecar.istio.io/inject: 'false' seems to be ignored when added to Deployment, need to add it to pod instead
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      sidecar.istio.io/inject: 'false'
    labels:
      app: web
      version: v1
    name: web
  spec:
    containers:
    - image: docker-registry.default.svc:5000/amazin-prod/web:v1
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: web
      ports:
      - containerPort: 8080
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: web
    name: web
  spec:
    ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
    selector:
      app: web
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: web
    name: web
  spec:
    port:
      targetPort: http
    tls:
      termination: edge
    to:
      kind: Service
      name: web
      weight: 100
    wildcardPolicy: None