apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

commonLabels:
  app: nginx-proxy

configMapGenerator:
- files:
  - proxy.conf
  name: proxy-conf

replicas:
- name: nginx-proxy
  count: 1
  
images:
- name: image
  newName: quay.io/justindav1s/nginx
  newTag: latest