apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: amazin-apimanager
  namespace: 3scale
spec:
  imageStreamTagImportInsecure: false
  resourceRequirementsEnabled: false
  system:
    database:
      postgresql: {}
    appSpec:
      replicas: 1
    sidekiqSpec:
      replicas: 1
  appLabel: 3scale-api-management
  zync:
    appSpec:
      replicas: 1
    queSpec:
      replicas: 1
  backend:
    cronSpec:
      replicas: 1
    listenerSpec:
      replicas: 1
    workerSpec:
      replicas: 1
  tenantName: 3scale
  apicast:
    managementAPI: status
    openSSLVerify: false
    productionSpec:
      replicas: 1
    responseCodes: true
    stagingSpec:
      replicas: 1
  wildcardDomain: apps.ocp4.datr.eu