apiVersion: v1
kind: Route
metadata:
  name: tls-istio-ingressgateway 
spec:
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  port:
    targetPort: 8443
  wildcardPolicy: None
  tls:
    termination: passthrough 