apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: copy-image-run
spec:
  serviceAccount: tkn-pipeline
  taskSpec:
    steps:
    - name: copy-and-push
      image: quay.io/rhpipeline/skopeo:alpine
      command:
      - skopeo
      args:
      - copy
      - docker://docker-registry.default.svc:5000/openshift/nodejs
      - docker://docker-registry.default.svc:5000/tekton-example/nodish
      - --src-tls-verify=false
      - --dest-tls-verify=false
  trigger:
    type: manual